Mise à jour des statuts suite à AGX du 18/02/2019
AgileFrance/AgileFrance.github.io pull request #32
Opened 2020-01-13 20:00 UTC by Makoti

2020-01-13 20:06 UTC, davidbgk commented on _pages/statuts.md
> +A ces fins, l’association entreprend toutes actions de promotion, de diffusion et d’éducation ayant trait aux pratiques dites agiles et aux approches et méthodes regroupant de telles pratiques; elle
`À ces fins` ?

2020-01-13 20:07 UTC, davidbgk commented on _pages/statuts.md
> +Cette association soutient la communauté agile francophone dans ses efforts pour faire évoluer la société vers plus d’efficacité, d’excellence, et de respect de tous les individus.
Je tique un peu sur l'excellence, je proposerai peut-être un amendement lors de la prochaine AG là-dessus.

2020-01-13 22:53 UTC, MattiSG commented on _pages/statuts.md
> +Cette association soutient la communauté agile francophone dans ses efforts pour faire évoluer la société vers plus d’efficacité, d’excellence, et de respect de tous les individus.
Je suis d'accord. Mais pour info, les statuts, c'est lourd à changer : ça se vote en AG, et ça s'envoie en préfecture… Si ça te gêne, je ne peux que te recommander de porter le sujet ASAP sur Loomio pour qu'on tente de mettre ce nouvel amendement dans ce train-ci 🙂

2020-01-14 08:34 UTC, MattiSG requested changes
Merci @Makoti !

Inclut, et donc closes #23, #26.

En revanche je ne retrouve pas dans ce patch plusieurs des propositions qui avaient me semble-t-il été votées, dont par exemple #18, et des parties de #21, #22, #24 (non-réadhésion suite à exclusion).

Il reste à :

- Ajouter un lien vers le manifeste agile (cf. #19).
- Ajouter une définition du scrutin majoritaire (cf. #29).

2020-01-14 08:34 UTC, MattiSG commented on _pages/statuts.md
> +Si ce·tte membre n’est pas ratifié au scrutin majoritaire simple, des candidatures individuelles peuvent être également présentées par d’autres membres.
> Pas certain de la pertinence de l'écriture inclusive sur « membre ».

2020-01-24 17:40 UTC, MattiSG commented
Réécrit et intégré via 28be5bd85dbc4a0a514743b4a403d6e0b39522a3.

2020-01-24 17:40 UTC, closed without merging