Ajoute le CR de l'AG 2020
AgileFrance/AgileFrance.github.io pull request #34
Opened 2020-03-08 08:30 UTC by krichtof

- formatte les notes prises au moment de l'AG

TODO : reste à joindre le bilan financier

2020-03-09 21:13 UTC, MattiSG approved these changes

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +Inquiétudes à cause de l'outil de paiement des billets, qui n'a pas versé près de 7000€. La réalisation de ce non-versement a été tardive. Cet outil ne sera pas renouvelé.
Les 7k€ ont été finalement reçus, ça a juste pris plusieurs mois. Cette formulation donne l'impression du contraire.

```suggestion
Inquiétudes à cause de l'outil de paiement des billets, qui n'a pas versé près de 7000€. La réalisation de ce non-versement a été tardive et il a fallu plusieurs mois pour les recouvrer. Cet outil ne sera pas renouvelé.
```

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +Départ en autonomie pour l'événement hiver, a priori avec la même équipe d'organisation dans une nouvelle association.
```suggestion
Départ en autonomie (sans demande de soutien à l'association Agile France) pour l'événement hiver, a priori avec la même équipe d'organisation dans une nouvelle association.
```

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +Les modalités de soutien on été décrite sur la page de l'association. \url{https://agile-france.org/}
Je ne connais pas cette syntaxe. C'est censé faire quoi ?
```suggestion
Les modalités de soutien on été décrite sur le [site de l'association](https://agile-france.org/).
```

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +Une subvention de 1000 euros a été accordée à l'initiative Mobilizon.
```suggestion
Une subvention de 1000 euros a été accordée à l'initiative Mobilizon, comme voté lors de l'AGX de juin 2019.
```

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +## Relation avec les adhérents
```suggestion
## Relation avec les adhérent‧e‧s
```

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +Frais de fonctionnement négligeables.
Donner un pourcentage pour objectiver cette assertion ?

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +- Christohe Robillard
```suggestion
- Christophe Robillard
```

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +Métriques : pas mis en place les outils de mesure nécessaires.
Je suis ok pour inclure ces éléments mais je ne suis pas certain que ça soit très compréhensible en l'état… ?

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +Pas le temps.
```suggestion
Pas le temps d'aborder des suggestions de modification en séance. Les changements devant être validés par une AG depuis le changement de statut, la discussion est remise à une séance ultérieure.
```

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +- quelles seraient les attentes des membres de l'association pour la dixième de la conférence ? Vos avis idées, suggestions, propositions, à titre informatif à communiquer à l'équipe d'orga
```suggestion
- quelles seraient les attentes des membres de l'association pour la dixième édition de la conférence ? Vos avis idées, suggestions, propositions, à titre informatif à communiquer à l'équipe d'orga
```

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +- provisionnement de lydia pour les dépenses de la conf
Pas certain de l'intérêt d'inclure ces notes en l'état car elles me semblent peu compréhensibles.

2020-03-09 21:13 UTC, MattiSG commented on _assemblee_generale/2020-02-15.md
> +[Bilan financier 2019](bilan-financier-global-2019.pdf)
> Ça serait trop cool à inclure directement en image vu qu'il n'y a que deux petits tableaux 🙂

2020-03-10 11:59 UTC, MattiSG requested changes
Il faut :

- Donner l'intitulé des postes de chacun des membres du bureau.
- Préciser que les membres du bureau sont habilité‧e‧s à engager financièrement l'association.
- Indiquer qui est responsable juridique (cf. statuts).

2020-03-10 19:02 UTC, krichtof commented on _assemblee_generale/2020-02-15.md
> +[Bilan financier 2019](bilan-financier-global-2019.pdf)
Tout à fait !

2020-03-10 19:08 UTC, krichtof commented on _assemblee_generale/2020-02-15.md
> +- provisionnement de lydia pour les dépenses de la conf
+1 pour supprimer cette partie

2020-03-10 19:15 UTC, krichtof commented on _assemblee_generale/2020-02-15.md
> +Métriques : pas mis en place les outils de mesure nécessaires.
Je trouve que ces éléments ont de la valeur. Et en même temps je n'ai pas de proposition de reformulation plus compréhensible...

2020-03-11 10:32 UTC, MattiSG approved these changes
J'ai ajouté par anticipation le nom du responsable juridique et l'habilitation à utiliser des intitulés de rôle de manière opportuniste dans 53a65c1, en faisant l'hypothèse que je serai reconduit dans cette responsabilité et que les membres se prononceront pour l'habilitation, afin de ne pas être bloquant pour le reste de la semaine.
Si les résultats des votes étaient différents, il suffira d'éditer ce qui a été ajouté dans ce commit 🙂

2020-03-14 10:57 UTC, MattiSG commented
Les votes ont confirmé la rédaction temporaire.

2020-03-14 10:57 UTC, merged